#!/bin/sh

sudo apt-get update
sudo apt-get install -y qemu-user-static
docker build -t raspi-kernel-builder .
docker run --env KCONFIG=/workdir/configs/bcm2709_defconfig_4_19_86 --rm -v "${PWD}":/workdir raspi-kernel-builder
docker run --env KCONFIG=/workdir/configs/bcmrpi_defconfig_4_19_86 --rm -v "${PWD}":/workdir raspi-kernel-builder
