#!/bin/sh

sudo apt-get update
sudo apt-get install -y qemu-user-static
docker build -t raspi-kernel-builder .
docker run --env --rm -v "${PWD}":/workdir raspi-kernel-builder
# The build script does not yet support armel builds.
