#!/bin/sh

sudo apt-get update
sudo apt-get install -y qemu-user-static
docker build -t raspi-kernel-builder .
#docker run -v "${PWD}":/workdir raspi-kernel-builder ./build-rpi3-kernel 0
docker run -v "${PWD}":/workdir raspi-kernel-builder ./build-rpi3-kernel 3
